/* CREAR BASE DE DATOS*/
CREATE DATABASE dl_GamarraMarket;

/* PONER EN USO LA BASE DE DATOS*/
USE dl_GamarraMarket;

/* ELIMINAR TABLA CLIENTE*/
DROP TABLE CLIENTE;

/* CREAR TABLA CLIENTE*/
CREATE TABLE CLIENTE
(
id INT,
tipo_documento CHAR(3),
numero_documento CHAR(15) NOT NULL,
nombres VARCHAR(60) NOT NULL,
apellidos VARCHAR(90) NOT NULL,
email VARCHAR(80) NOT NULL,
celular CHAR(9) NOT NULL,
fecha_nacimiento DATE,
activo BOOL,
CONSTRAINT id_PK PRIMARY KEY(id)
);

/* LISTAR ESTRUCTURA DE TABLA CLIENTE*/
SHOW COLUMNS IN CLIENTE;

/* LISTAR TABLAS EXISTENTES EN LA BASE DE DATOS EN USO*/
SHOW TABLES;

/* AGREGAR COLUMNA ESTADO CIVIL*/
ALTER TABLE CLIENTE
	ADD COLUMN estado_civil char(1);
    
/* ELIMINAR COLUMNA fecha_nacimiento*/
ALTER TABLE CLIENTE
	DROP COLUMN fecha_nacimiento;

/* CREAR TABLA VENTA*/
CREATE TABLE VENTA
(
id INT,
fecha_hora TIMESTAMP,
activo BOOL,
cliente_id INT NOT NULL,
vendedor_id INT NOT NULL,
CONSTRAINT id_PK PRIMARY KEY(id)
);

/* LISTAR ESTRUCTURA DE TABLA VENTA*/
SHOW COLUMNS IN VENTA;

/* CREAR TABLA VENDEDOR*/
CREATE TABLE VENDEDOR
(
id INT,
tipo_documento CHAR(3) NOT NULL,
numero_documento CHAR(15) NOT NULL,
nombres VARCHAR(60) NOT NULL,
apellidos VARCHAR(90) NOT NULL,
salario DECIMAL(8,2) NOT NULL,
celular CHAR(9) NOT NULL,
email VARCHAR(80) NOT NULL,
activo BOOL,
CONSTRAINT id_PK PRIMARY KEY(id)
);

/* LISTAR ESTRUCTURA DE TABLA VENDEDOR*/
SHOW COLUMNS IN VENDEDOR;

/* CREAR TABLA VENTA_DETALLE*/
CREATE TABLE VENTA_DETALLE
(
id INT,
cantidad INT,
venta_id INT,
prenda_id INT,
CONSTRAINT id_PK PRIMARY KEY(id)
);

/* LISTAR ESTRUCTURA DE TABLA VENTA_DETALLE*/
SHOW COLUMNS IN VENTA_DETALLE;

/* CREAR TABLA PRENDA*/
CREATE TABLE PRENDA
(
id INT,
descripción VARCHAR(90) NOT NULL,
marca VARCHAR(60) NOT NULL,
cantidad INT,
talla VARCHAR(10) NOT NULL,
precio DECIMAL(8,2) NOT NULL,
activo BOOL,
CONSTRAINT id_PK PRIMARY KEY(id)
);

/* LISTAR ESTRUCTURA DE TABLA PRENDA*/
SHOW COLUMNS IN PRENDA;

/* CREAR RELACIÓN VENTA_CLIENTE */
ALTER TABLE VENTA
	ADD CONSTRAINT VENTA_CLIENTE FOREIGN KEY (cliente_id)
    REFERENCES CLIENTE (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
;

/* CREAR RELACIÓN VENTA_VENDEDOR */
ALTER TABLE VENTA
	ADD CONSTRAINT VENDEDOR_VENTA FOREIGN KEY (vendedor_id)
    REFERENCES VENDEDOR (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
;

ALTER TABLE VENTA
	DROP CONSTRAINT VENDEDOR_CLIENTE;

/* CREAR RELACIÓN PRENDA_VENTA_DETALLE */
ALTER TABLE VENTA_DETALLE
	ADD CONSTRAINT PRENDA_VENTA_DETALLE FOREIGN KEY (prenda_id)
    REFERENCES PRENDA (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
;

/* CREAR RELACIÓN VENTA_VENTA_DETALLE */
ALTER TABLE VENTA_DETALLE
	ADD CONSTRAINT VENTA_VENTA_DETALLE FOREIGN KEY (venta_id)
    REFERENCES VENTA (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
;

/* ELIMINAR LA RELACIÓN VENTA_VENTA_DETALLE*/
ALTER TABLE VENTA
	DROP CONSTRAINT VENTA_VENTA_CLIENTE;
    
/* Listar relaciones de tablas de la base de datos activa */
SELECT 
    i.constraint_name, k.table_name, k.column_name, 
    k.referenced_table_name, k.referenced_column_name
FROM 
    information_schema.TABLE_CONSTRAINTS i 
LEFT JOIN information_schema.KEY_COLUMN_USAGE k 
ON i.CONSTRAINT_NAME = k.CONSTRAINT_NAME 
WHERE i.CONSTRAINT_TYPE = 'FOREIGN KEY' 
AND i.TABLE_SCHEMA = DATABASE();